//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesData
    {
        public int ID { get; set; }
        public Nullable<decimal> LineNetTotal { get; set; }
        public Nullable<decimal> LineNet { get; set; }
        public Nullable<int> BranchNr { get; set; }
        public string Branch { get; set; }
        public string Salesman { get; set; }
        public string City { get; set; }
        public string Region { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<int> ClientCode { get; set; }
        public string ClientName { get; set; }
        public Nullable<int> BrandCode { get; set; }
        public string Brand { get; set; }
        public string CategoryName1 { get; set; }
        public string CategoryName2 { get; set; }
        public string CategoryName3 { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Gender { get; set; }
    }
}
